version: '3.7'
services:
  db:
    image: mariadb:latest
    container_name: database
    ports:
      - "${HOST_MYSQL_PORT}:${CONTAINER_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASS}
    volumes:
      - ${HOST_CUSTOM_CONF}:${CONTAINER_CUSTOM_CONF}
    networks:
      - internal

  php:
    build: ./docker/php
    container_name: php
    ports:
      - "${HOST_FPM_PORT}:${CONTAINER_FPM_PORT}"
    volumes:
      - ${HOST_WEB_BASEDIR}:${CONTAINER_WEB_BASEDIR}:cached
    links:
      - db
    networks:
      - internal
      - external

  nginx:
    build: ./docker/nginx
    container_name: web
    ports:
      - "${HOST_WEB_PORT}:${CONTAINER_WEB_PORT}"
    links:
      - php
    volumes:
      - ${NGINX_HOST_LOGS_BASEDIR}:${NGINX_CONTAINER_LOGS_BASEDIR}:cached
      - ${HOST_WEB_BASEDIR}:${CONTAINER_WEB_BASEDIR}:cached
    networks:
      - external

networks:
  internal:
  external:
